# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 032fc7ca0e1e558f1f6c1638a2b1a06d16cd1b86cbe4e05e0f795c74ef8f732bf19bd204ec991952715dda3aa75957f001040da9c1c618da4512c5d725bbcf73

test:
  secret_key_base: 25c61f261464e03acfc010346a03bbd000e67251c5501a1d15aee33dc4ac9e0fadae6efc326806ae35de9f6bdd5d44dd6375a52bd39d9de222d592f656473f19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
